kumuluzee:
  ...
  datasources:
      - jndi-name: jdbc/NakupovalniSeznamiDS
        connection-url: jdbc:postgresql://192.168.44.130/nakupovalniseznami
        username: postgres
        password: postgres
        max-pool-size: 20